### ISSUE TITLE
Meta Checker

### ISSUE THREAD

**Issue by miqdadyyy** [cmlabsdev/tools#411]
- [x] Enable text field from auto to manual
- [x] Indicator not work
- [x] Need to add ellipsis when word is too long

**Comment by WisnuDS** [comment]
close pls
